In [1]:
import numpy as np

In [7]:
weights = np.random.randn(2)


In [8]:
weights

array([ 1.12841188, -0.72494392])

In [9]:
input_vector = np.array([[2,0],[1,2],[3,2],[5,0]])
output_vector = [0,1,1,0]

In [10]:
input_vector.shape

(4, 2)

In [11]:
summation_formula = np.dot(input_vector,weights)

In [12]:
summation_formula

array([ 2.25682376, -0.32147597,  1.93534779,  5.6420594 ])

In [15]:
test_arr = np.array([1,2,-2,0,-3])
result = test_arr>=0


In [17]:
result.astype(int)

array([1, 1, 0, 1, 0])

In [33]:
error = np.array([0.1,-0.1,0.2,-0.2])
print(error.shape)
learning_rate = 0.1

(4,)


In [34]:
print(input_vector)


[[2 0]
 [1 2]
 [3 2]
 [5 0]]


In [35]:
print(input_vector.shape)

(4, 2)


In [36]:
abc = np.dot(input_vector.T,error)
abc

array([-0.3,  0.2])

In [25]:
weights = weights+ learning_rate * abc

In [26]:
weights

array([ 1.14241188, -0.73294392])