## Numpy Basics 

In [9]:
#import numpy
import numpy as np

### 1. np.radom.randint(low,high,size)
<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_1.jpeg" width="600">

### 2. Creating a numpy array from a list and finding its shape

In [10]:
list1 = [1,2,3]
numpy_array = np.array(list1)
print("Numpy array :",numpy_array)
print("Shape of array :",numpy_array.shape)


Numpy array : [1 2 3]
Shape of array : (3,)


### Zero Array and Ones Array

##### Give the size of array and all its values will be filled with zeros or ones

In [11]:
#Zero array
z = np.zeros((2,3))
print("Zero 2-d array :", z)

#Ones Array
o = np.ones((2,3))
print("Ones 2-d array :",o)


Zero 2-d array : [[0. 0. 0.]
 [0. 0. 0.]]
Ones 2-d array : [[1. 1. 1.]
 [1. 1. 1.]]


## Numpy Indexing and Slicing Operations

In [12]:
a = np.array([10, 20, 30, 40, 50])

print("Element at 3rd position : ",a[2])
print("Elements from 1st position to 3rd position :",a[:3])

m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m[1, 2]     # row 1, col 2 -> 6
m[0]        # entire row 0 -> [1,2,3]
m[:, 1]     # entire column 1 -> [2,5,8]
m[0:2, 1:3] # rows 0-1, cols 1-2 -> [[2,3],[5,6]]


Element at 3rd position :  30
Elements from 1st position to 3rd position : [10 20 30]


array([[2, 3],
       [5, 6]])

## Broadcasting in Numpy

<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_2.jpeg" width="600">

In [19]:
a = np.array([1, 2, 3])
print(a + 5)          # [6, 7, 8]  -- 5 is "stretched" to [5,5,5]

[6 7 8]


In [20]:
m = np.array([[1,2,3],
              [4,5,6]])          # shape (2,3)
v = np.array([10, 20, 30])       # shape (3,)

print(m + v)
# [[11,22,33],
#  [14,25,36]]

[[11 22 33]
 [14 25 36]]


<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_3.jpeg" width="500">


<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_4.jpeg" width="500">

In [18]:
A = np.ones((1,3))    # shape (3,1)
B = np.ones((4,1))    # shape (1,4)
result = A + B
print(result)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


## Understading Numpy Using a Project 

<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_5.jpeg" width="500">

In [23]:
#creating seperate arrays for each column

order_id = np.arange(1,100001,1)
product_id = np.random.randint(1,101,100000)
customer_id = np.random.randint(1,10001,100000)
product_price = np.random.randint(5,501,100000)
discount = np.random.randint(0,31,100000)
qty = np.random.randint(1,6,100000)




In [24]:
print("Order ID: ",order_id)
print("----------")
print("Prodcut ID: ",product_id)
print("----------")
print("Customer ID: ",customer_id)
print("----------")
print("Price: ",product_price)

print("----------")
print("Quantity: ",qty)
print("----------")

print("Discount: ",discount)

Order ID:  [     1      2      3 ...  99998  99999 100000]
----------
Prodcut ID:  [38 25 10 ...  1 45 92]
----------
Customer ID:  [6195 6807 8296 ... 6158 8565 9654]
----------
Price:  [ 92  99 141 ... 342 226 128]
----------
Quantity:  [3 5 2 ... 3 1 4]
----------
Discount:  [17 25 13 ... 17  8 10]


<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_6.jpeg" width="500">

In [28]:
# 1. What is total revenue generated from all orders ?
modified_discount = discount/100
revenue = qty*product_price * 1-modified_discount
print("Total Revenue: ",revenue.sum())

Total Revenue:  75943770.07000001


In [39]:
# What is the Average Revenue per order ?

# avg_revenue = total_revenue/total_orders
total_revenue = revenue.sum()
total_orders = order_id.size
avg_revenue = total_revenue/total_orders
print("Average Revenue: ",avg_revenue)

Average Revenue:  759.4377007


In [ ]:
#how many orders generated more than 500 euros in revenue after discount ?

print(" Total orders that generated more than 500 euros in revenue after discount :",(revenue>500).sum())


#another way to do this 
revenue_more_500 = revenue[revenue>500]
revenue_more_500
total_such_order = revenue_more_500.size


 Total orders that generated more than 500 euros in revenue after discount : 55111


55111

In [48]:
#which orders generated revenue greater than 500 euros and has a discount of less than 10%

mask = (revenue>500) & (discount<10)
order_id[mask]

array([    4,     7,    12, ..., 99977, 99988, 99997], shape=(17965,))

### argmax() gives you the position (index) of the largest value in an array.

<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_7.jpeg" width="500">

In [53]:
#which order generated the maximum revenue ?

max_id = revenue.argmax()
print("Order ID of max revenue order: ",order_id[max_id])
print("Revenue generated: ",revenue[max_id])

Order ID of max revenue order:  91537
Revenue generated:  2500.0


In [54]:
#Which 10 customers generated the most revenue?

all_customer_revenue = np.bincount(customer_id,weights=revenue)
all_customer_revenue_sorted_map = np.argsort(all_customer_revenue)
top_10_customer =all_customer_revenue_sorted_map[-10:]
top_10_customer

array([4783, 6263, 5926, 6242, 1387, 7572, 9198, 1334,  262, 2724])

##### END