In [1]:
import numpy as np

In [2]:
demo_weights = np.random.randn(3,1)

In [3]:
demo_weights

array([[-0.2956938 ],
       [ 0.43168711],
       [-0.94712553]])

In [6]:
class Neuron():

    def __init__(self,num_inputs):
        self.weight_matrix = np.random.randn(num_inputs,1)
        self.bias = 1

    def _ReLu(z):
        return max(0,z)

    def _Sigmoid(z):
        pass

    def _tanh(z):
        pass

        
    def forward(self,input,activation):
        sum_total = np.dot(input,self.weight_matrix)+self.bias
        print(sum_total)
        if activation=='relu':
            z = self._ReLu(sum_total)
            return z
        elif activation=='sigmoid':
            pass
        elif activation=='tanh':
            pass

In [7]:
neuron = Neuron(2)

input = np.array([[1,2],
                  [2,3],
                  [2,4]])

neuron.forward(input=input,activation='relu')


[[-1.07277046]
 [-2.302465  ]
 [-3.14554092]]


TypeError: Neuron._ReLu() takes 1 positional argument but 2 were given

In [19]:
num_neurons = 4
num_input = 2
demo_w = np.random.randn(num_input,num_neurons)
demo_w.shape
inp = np.array([[2,3]])

print(inp.shape)
abc = np.dot(inp,demo_w)
print(abc)


(1, 2)
[[-2.25574159  2.4502174   7.17718263 -1.10829226]]


In [ ]:
class Dense():

    def __init__(self,num_neuron,num_inputs):
        self.weights = np.random.randn(num_inputs,num_neuron)
        self.bias = np.random.randn(1,num_neuron)


    def forward(self,input_matrix):
        print("Bias:",self.bias)
        sum = np.dot(input_matrix,self.weights)+self.bias
        return sum

    def fit(self,ephocs):

        #loop till those ephocs
        for i in range()




In [31]:
layer1 = Dense(4,2)
layer1.forward(inp)

Bias: [[-1.22496703  1.18861297 -0.18035877  1.18823604]]


array([[-0.92291336,  0.893657  , -6.03857776, -6.81407874]])