# Dataset Requirements

Create a dataset containing **1,00,000 orders** with the following columns:

| Column | Description |
|---|---|
| `order_id` | Unique ID for each order |
| `customer_id` | ID of the customer |
| `product_id` | ID of the product |
| `product_price` | Price of the product in euros |
| `qty` | Quantity ordered |
| `discount` | Discount percentage |

## Assumptions

- **Total Orders:** 1,00,000
- **Total Customers:** 10,000
- **Total Products:** 100
- **Quantity (`qty`):** 1–5
- **Product Price (`product_price`):** €5–€500
- **Discount (`discount`):** 0%–30%

In [3]:
import numpy as np


In [4]:
order_id = np.arange(1,100001,1)
product_id = np.random.randint(1,101,100000)
customer_id = np.random.randint(1,10001,100000)
product_price = np.random.randint(5,501,100000)
discount = np.random.randint(0,31,100000)
qty = np.random.randint(1,6,100000)




In [5]:
print(order_id)
print("----------")
print(product_id)
print("----------")
print(customer_id)
print("----------")
print(product_price)

print("----------")
print(qty)
print("----------")

print(discount)

[     1      2      3 ...  99998  99999 100000]
----------
[ 44  14  62 ...  95 100  93]
----------
[3694 1342 3581 ...  236  168 6595]
----------
[433 466 141 ... 166 400 499]
----------
[4 5 1 ... 1 4 4]
----------
[15  4 11 ...  8 27 11]


#Revenue calculation 

Revenue=Quantity×Price×(1−Discount/100)

In [6]:
modified_discount = discount/100
revenue = qty*product_price * 1-modified_discount

In [7]:
revenue

array([1731.85, 2329.96,  140.89, ...,  165.92, 1599.73, 1995.89],
      shape=(100000,))

In [8]:
total_revenue = revenue.sum()
print("Total Revenue :",int(total_revenue))

average_order_revenue = int(total_revenue)/100000
print("Average Revenue : ",int(average_order_revenue))

Total Revenue : 75725320
Average Revenue :  757


In [14]:
# all transcation where revenue after discount was more than 500 euros

revenue_more_500 = revenue[revenue>500]
revenue_more_500
total_such_order = revenue_more_500.size
total_such_order

54861

In [15]:
# which order generated revenue more than 500

mask1 = revenue>500
print(order_id[mask1])

[     1      2      4 ...  99996  99999 100000]


In [20]:
#Find orders where revenue was greater than €500 AND the discount was less than 10%.
mask2 = (revenue>500) & (discount<10)
print(revenue[mask2])

[2329.96  935.92  967.96 ... 1404.91 1989.91  854.91]


In [28]:
revenue.argmax()

np.int64(16897)

In [29]:
#What are the 10 highest-revenue orders, and what are their order IDs?

mask3 = revenue.argsort()
inds = mask3[-10:]
order_id[inds]


array([39690,  7867, 74194,  5074, 17986, 42682,  1087, 79244, 16898,
       41841])

In [ ]:
#Which 10 customers generated the most revenue?

all_customer_revenue = np.bincount(customer_id,weights=revenue)
all_customer_revenue_sorted_map = np.argsort(all_customer_revenue)
top_10_customer =all_customer_revenue_sorted_map[-10:]
top_10_customer

array([3694, 6172, 5253, 4306, 2006, 9272, 9798, 3482, 5192,  874])