## Numpy Revision


## `np.random.randint()` — Key Concept

**Signature:**
```python
np.random.randint(low, high=None, size=None)
```

- If `high` is `None` → `low` becomes the **exclusive upper bound**, range starts at 0.
- If `low` is passed as a **tuple/array-like** → numpy treats each element as its own separate upper bound, and returns **one random number per element**.
- ⚠️ This is broadcasting-like behavior — it does NOT mean "rows/cols/batch size."

### Example: tuple as `low`
```python## `np.random.randint()` — Key Concept

**Signature:**
```python
np.random.randint(low, high=None, size=None)
```

- If `high` is `None` → `low` becomes the **exclusive upper bound**, range starts at 0.
- If `low` is passed as a **tuple/array-like** → numpy treats each element as its own separate upper bound, and returns **one random number per element**.
- ⚠️ This is broadcasting-like behavior — it does NOT mean "rows/cols/batch size."

### Example: tuple as `low`
```python
np.random.randint((5, 100, 3, 1000))
# Result: [3, 12, 0, 767]
```
| Position | Tuple value (bound) | Range     | Output |
|----------|----------------------|-----------|--------|
| 0        | 5                    | [0, 5)    | 3      |
| 1        | 100                  | [0, 100)  | 12     |
| 2        | 3                    | [0, 3)    | 0      |
| 3        | 1000                 | [0, 1000) | 767    |

**Rule of thumb:** output length = length of the tuple passed as `low`. Each element defines its own independent `[0, bound)` range.

---

### The "normal" / explicit usage
```python
np.random.randint(0, 10, 2)
```
Here the three positional args map cleanly to `low=0`, `high=10`, `size=2`.

- `low = 0` → range starts at 0
- `high = 10` → range ends before 10 (exclusive)
- `size = 2` → return **2** random integers, each independently drawn from `[0, 10)`

Example output: `[7, 2]` — both numbers come from the *same* range `[0, 10)`, unlike the tuple case where each position had its *own* range.

### Side-by-side comparison
| Call                                  | What each number represents                        | Output length |
|----------------------------------------|------------------------------------------------------|----------------|
| `np.random.randint((5, 100, 3))`      | one number per **different** upper bound             | 3 (= tuple len)|
| `np.random.randint(0, 10, 2)`         | 2 numbers from the **same** `[0, 10)` range           | 2 (= `size`)   |

**Takeaway:** `size` controls "how many," `low`/`high` control "what range." Passing a tuple as `low` overloads that meaning via broadcasting — easy to do by accident, hard to spot the bug.
np.random.randint((5, 100, 3, 1000))
# Result: [3, 12, 0, 767]
```
| Position | Tuple value (bound) | Range     | Output |
|----------|----------------------|-----------|--------|
| 0        | 5                    | [0, 5)    | 3      |
| 1        | 100                  | [0, 100)  | 12     |
| 2        | 3                    | [0, 3)    | 0      |
| 3        | 1000                 | [0, 1000) | 767    |

**Rule of thumb:** output length = length of the tuple passed as `low`. Each element defines its own independent `[0, bound)` range.

---

### The "normal" / explicit usage
```python
np.random.randint(0, 10, 2)
```
Here the three positional args map cleanly to `low=0`, `high=10`, `size=2`.

- `low = 0` → range starts at 0
- `high = 10` → range ends before 10 (exclusive)
- `size = 2` → return **2** random integers, each independently drawn from `[0, 10)`

Example output: `[7, 2]` — both numbers come from the *same* range `[0, 10)`, unlike the tuple case where each position had its *own* range.

### Side-by-side comparison
| Call                                  | What each number represents                        | Output length |
|----------------------------------------|------------------------------------------------------|----------------|
| `np.random.randint((5, 100, 3))`      | one number per **different** upper bound             | 3 (= tuple len)|
| `np.random.randint(0, 10, 2)`         | 2 numbers from the **same** `[0, 10)` range           | 2 (= `size`)   |

**Takeaway:** `size` controls "how many," `low`/`high` control "what range." Passing a tuple as `low` overloads that meaning via broadcasting — easy to do by accident, hard to spot the bug.

### Basic Numpy Array Operations

In [1]:
import numpy as np


In [ ]:
list1 = [1,2,3]
numpy_array = np.array(list1)
print("Numpy array :",numpy_array)
print("Shape of array :",numpy_array.shape)

#Zero array
z = np.zeros((2,3))
print("Zero 2-d array :", z)

# similiarly there is 1s array



Numpy array : [1 2 3]
Shape of array : (3,)
Zero 2-d array : [[0. 0. 0.]
 [0. 0. 0.]]


### Numpy Indexing and Slicing Operations

In [9]:
a = np.array([10, 20, 30, 40, 50])

print("Element at 3rd position : ",a[2])
print("Elements from 1st position to 3rd position :",a[:3])

m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m[1, 2]     # row 1, col 2 -> 6
m[0]        # entire row 0 -> [1,2,3]
m[:, 1]     # entire column 1 -> [2,5,8]
m[0:2, 1:3] # rows 0-1, cols 1-2 -> [[2,3],[5,6]]


Element at 3rd position :  30
Elements from 1st position to 3rd position : [10 20 30]


array([[2, 3],
       [5, 6]])

### Broadcasting in Numpy 

In [11]:
a = np.array([1, 2, 3])
print(a + 5)          # [6, 7, 8]  -- 5 is "stretched" to [5,5,5]

[6 7 8]


In [12]:
m = np.array([[1,2,3],
              [4,5,6]])          # shape (2,3)
v = np.array([10, 20, 30])       # shape (3,)

print(m + v)
# [[11,22,33],
#  [14,25,36]]

[[11 22 33]
 [14 25 36]]


In [13]:
A = np.ones((3, 1))    # shape (3,1)
B = np.ones((1, 4))    # shape (1,4)
result = A + B
print(result)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
