NUMPY 


In [12]:
! /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 446.1 kB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip


In [13]:
import numpy as np


### Creating Arrays from List

In [14]:
array_1d = np.array([1,2,3])
print("1D Array :",array_1d)

array_2d = np.array([[1,2,3],[2,4,5]])
print("2D Array :",array_2d)


1D Array : [1 2 3]
2D Array : [[1 2 3]
 [2 4 5]]


### Zeros Array

In [15]:
zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
array_ones = np.ones((8,3))
print(array_ones)

#special constant array
print("\n")
special = np.full((2,5),4)
print("\n special array :",special)

#sequence Array
sequence = np.arange(0,12,2)
print("\n sequence Array :",sequence)

#Random array
random_ar = np.random.randint((2,30,42,))
print("\n Random array :",random_ar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



 special array : [[4 4 4 4 4]
 [4 4 4 4 4]]

 sequence Array : [ 0  2  4  6  8 10]

 Random array : [ 0  6 31  4]


## Vector Matrix and tensors


In [ ]:
vector = np.array([1,2,3])
print("\n Vector :",vector)

Matrix = np.array([[1,2,3],
                   [3,5,3],
                   [1,5,4]
                   ])
print("\n Matrix :",Matrix)

Tensor = np.array([[[1,2],[3,4]],
                    [[3,4],[6,7]],
                    [[2,2],[4,5]],
                    ])
print("\n Tensor : ",Tensor)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' on line 10 (409781756.py, line 13)